Version2
YunoHost-Apps/timemachine_ynh pull request #5
Opened 2023-12-21 17:14 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-12-21 17:14 UTC, ericgaspar commented
!testme

2024-01-14 15:29 UTC, Salamandar requested changes

2024-01-14 15:29 UTC, Salamandar commented on scripts/remove
> -	ynh_exec_warn_less yunohost firewall disallow TCP 445
You're not closing the port anymore?

2024-01-14 15:29 UTC, Salamandar commented on scripts/restore
>  # RESTORE VARIOUS FILES
You should yunohost firewall allow on restore too

2024-01-14 15:29 UTC, Salamandar commented on scripts/upgrade
Same here, maybe run yunohost firewall allow

2024-01-14 15:35 UTC, ericgaspar commented
!testme

2024-01-14 15:43 UTC, merged